### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by Riders004** [Guru322/Any-dl#4]
Any second api or codes ofr yt or alternative of https://tomp3.cc/api/ajax
Due to distube Ytdl core is giving warning

**Comment by Guru322** [comment]
you get those warning on a shared ip

https://api.guruapi.tech/ytdl/ytmp4?url=https://youtu.be/Rcu2AAjdTjE?si=7MpbBjc-kBVUJx3l

i don't get those errors on a vm with dedicated ip

**Comment by Guru322** [comment]
alternatively use 
https://github.com/ybd-project/ytdl-core

**Comment by Riders004** [comment]
> you get those warning on a shared ip
> 
> https://api.guruapi.tech/ytdl/ytmp4?url=https://youtu.be/Rcu2AAjdTjE?si=7MpbBjc-kBVUJx3l
> 
> i don't get those errors on a vm with dedicated ip

It's ask to sign in to confirm you're not a bot well I have AWS RDP server

**Comment by Riders004** [comment]
> alternatively use https://github.com/ybd-project/ytdl-core

404 not found

**Comment by Guru322** [comment]
> > you get those warning on a shared ip
> > https://api.guruapi.tech/ytdl/ytmp4?url=https://youtu.be/Rcu2AAjdTjE?si=7MpbBjc-kBVUJx3l
> > i don't get those errors on a vm with dedicated ip
> 
> It's ask to sign in to confirm you're not a bot well I have AWS RDP server

https://github.com/TeamPiped/Piped/issues/3658#issuecomment-2367959839

https://github.com/iv-org/invidious/issues/4734#issuecomment-2365205990
